//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaryanaGK
    {
        public int id { get; set; }
        public string Question { get; set; }
        public string Answere { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
